name: IICS CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Informatica CLI
      uses: informatica/infa-cli-setup-action@v1
      with:
        informatica_cli_version: '10.4.2'

    - name: Build IICS Assets
      run: |
        # Use Informatica CLI commands to build your IICS assets
        informatica cloud createbundle -s Explore/TEST_CASE  -b test_mapping
      env:
        INFA_USER_NAME: ${{ secrets.INFA_USER_NAME }}
        INFA_USER_PASSWORD: ${{ secrets.INFA_USER_PASSWORD }}
        INFA_ORG_NAME: ${{ secrets.INFA_ORG_NAME }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: iics-artifacts
        path: Explore/TEST_CASE

  # Add more jobs or steps for testing and other CI tasks as needed
